#!/bin/bash -l 
#SBATCH -p debug
#SBATCH -N 1
#SBATCH -t 00:01:00 
#SBATCH -J Blocked_job 
#SBATCH -o MyBlockedOutputFile.%j.out
#SBATCH -e MyBlockedErrorFile.%j.err
#SBATCH --vtune
module load vtune

srun -n 1 amplxe-cl -collect general-exploration -r $SCRATCH/res_dir --trace-mpi -- ./benchmark-blocked

